spring.application.name=surftracker-API
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/surftracker_db
spring.datasource.username=postgres
spring.datasource.password=leoelias123
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql= true
spring.jpa.open-in-view = true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug

server.port = 8091